name: Build and Archive Quarkus App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tagging the version
        id: semantic
        uses: paulhatch/semantic-version@v5.3.0

      - name: Outputing the version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.version }}
